ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ACc;


INSERT INTO ACc.contests VALUES(1,7,DEFAULT,NULL,2165);
INSERT INTO ACc.contests VALUES(2,8,DEFAULT,NULL,1707);
INSERT INTO ACc.contests VALUES(3,6,DEFAULT,NULL,1752);
INSERT INTO ACc.contests VALUES(4,7,DEFAULT,NULL,870);
INSERT INTO ACc.contests VALUES(5,8,DEFAULT,NULL,1191);
INSERT INTO ACc.contests VALUES(6,6,DEFAULT,NULL,1567);
INSERT INTO ACc.contests VALUES(7,7,DEFAULT,NULL,1810);
INSERT INTO ACc.contests VALUES(8,8,DEFAULT,NULL,2257);
INSERT INTO ACc.contests VALUES(9,6,DEFAULT,NULL,1300);

INSERT INTO ACc.submissions VALUES(DEFAULT,'A','AC',DEFAULT,1,0);
INSERT INTO ACc.submissions VALUES(DEFAULT,'B','AC',DEFAULT,1,0);
INSERT INTO ACc.submissions VALUES(DEFAULT,'C','AC',DEFAULT,1,0);
INSERT INTO ACc.submissions VALUES(DEFAULT,'D','AC',DEFAULT,1,0);
INSERT INTO ACc.submissions VALUES(DEFAULT,'E','AC',DEFAULT,1,0);
INSERT INTO ACc.submissions VALUES(DEFAULT,'F','AC',DEFAULT,1,0);

INSERT INTO ACc.submissions VALUES(DEFAULT,'A','AC',DEFAULT,1,2);

INSERT INTO ACc.submissions VALUES(DEFAULT,'A','AC',DEFAULT,1,3);

INSERT INTO ACc.submissions VALUES(DEFAULT,'A','AC',DEFAULT,1,4);
INSERT INTO ACc.submissions VALUES(DEFAULT,'B','AC',DEFAULT,1,4);
INSERT INTO ACc.submissions VALUES(DEFAULT,'C','AC',DEFAULT,1,4);
INSERT INTO ACc.submissions VALUES(DEFAULT,'D','AC',DEFAULT,1,4);
INSERT INTO ACc.submissions VALUES(DEFAULT,'E','AC',DEFAULT,1,4);

INSERT INTO ACc.submissions VALUES(DEFAULT,'A','AC',DEFAULT,1,5);
INSERT INTO ACc.submissions VALUES(DEFAULT,'B','AC',DEFAULT,1,5);
INSERT INTO ACc.submissions VALUES(DEFAULT,'C','AC',DEFAULT,1,5);
INSERT INTO ACc.submissions VALUES(DEFAULT,'D','AC',DEFAULT,1,5);
INSERT INTO ACc.submissions VALUES(DEFAULT,'F','AC',DEFAULT,1,5);

INSERT INTO ACc.submissions VALUES(DEFAULT,'A','AC',DEFAULT,1,7);

INSERT INTO ACc.submissions VALUES(DEFAULT,'A','AC',DEFAULT,1,9);

COMMIT;