ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = cac;


INSERT INTO cac.contests VALUES(1,7,DEFAULT,NULL,2165,".");
INSERT INTO cac.contests VALUES(2,8,DEFAULT,NULL,1707,".");
INSERT INTO cac.contests VALUES(3,6,DEFAULT,NULL,1752,".");
INSERT INTO cac.contests VALUES(4,7,DEFAULT,NULL,870,".");
INSERT INTO cac.contests VALUES(5,8,DEFAULT,NULL,1191,".");
INSERT INTO cac.contests VALUES(6,6,DEFAULT,NULL,1567,".");
INSERT INTO cac.contests VALUES(7,7,DEFAULT,NULL,1810,".");
INSERT INTO cac.contests VALUES(8,8,DEFAULT,NULL,2257,".");
INSERT INTO cac.contests VALUES(9,6,DEFAULT,NULL,1300,".");

INSERT INTO cac.submissions VALUES(DEFAULT,'A','AC',DEFAULT,0,0);
INSERT INTO cac.submissions VALUES(DEFAULT,'B','AC',DEFAULT,0,0);
INSERT INTO cac.submissions VALUES(DEFAULT,'C','AC',DEFAULT,0,0);
INSERT INTO cac.submissions VALUES(DEFAULT,'D','AC',DEFAULT,0,0);
INSERT INTO cac.submissions VALUES(DEFAULT,'E','AC',DEFAULT,0,0);
INSERT INTO cac.submissions VALUES(DEFAULT,'F','AC',DEFAULT,0,0);

INSERT INTO cac.submissions VALUES(DEFAULT,'A','AC',DEFAULT,0,2);

INSERT INTO cac.submissions VALUES(DEFAULT,'A','AC',DEFAULT,0,3);

INSERT INTO cac.submissions VALUES(DEFAULT,'A','AC',DEFAULT,0,4);
INSERT INTO cac.submissions VALUES(DEFAULT,'B','AC',DEFAULT,0,4);
INSERT INTO cac.submissions VALUES(DEFAULT,'C','AC',DEFAULT,0,4);
INSERT INTO cac.submissions VALUES(DEFAULT,'D','AC',DEFAULT,0,4);
INSERT INTO cac.submissions VALUES(DEFAULT,'E','AC',DEFAULT,0,4);

INSERT INTO cac.submissions VALUES(DEFAULT,'A','AC',DEFAULT,0,5);
INSERT INTO cac.submissions VALUES(DEFAULT,'B','AC',DEFAULT,0,5);
INSERT INTO cac.submissions VALUES(DEFAULT,'C','AC',DEFAULT,0,5);
INSERT INTO cac.submissions VALUES(DEFAULT,'D','AC',DEFAULT,0,5);
INSERT INTO cac.submissions VALUES(DEFAULT,'F','AC',DEFAULT,0,5);

INSERT INTO cac.submissions VALUES(DEFAULT,'A','AC',DEFAULT,0,7);

INSERT INTO cac.submissions VALUES(DEFAULT,'A','AC',DEFAULT,0,9);

COMMIT;